OrdererOrgs:
  - Name: Orderer
    Domain: arch.nl
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: Org1
    Domain: org1.arch.nl
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1

  - Name: Org2
    Domain: org2.arch.nl
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1

  - Name: Org3
    Domain: org3.arch.nl
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1
