OrdererOrgs:
  - Name: Orderer
    Domain: hva.nl
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: bc
    Domain: bc.hva.nl
    EnableNodeOUs: true
    Template:
      Count: 5
    Users:
      Count: 1
