# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  hvanet:

services:
  couchdb0:
    container_name: couchdb0
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - "5984:5984"
    networks:
      - hvanet

  peer0.bc.hva.nl:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    depends_on:
      - couchdb0

  couchdb1:
    container_name: couchdb1
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - "6984:5984"
    networks:
      - hvanet

  peer1.bc.hva.nl:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    depends_on:
      - couchdb1

  # couchdb2:
  #   container_name: couchdb2
  #   image: hyperledger/fabric-couchdb
  #   environment:
  #     - COUCHDB_USER=
  #     - COUCHDB_PASSWORD=
  #   ports:
  #     - "7984:5984"
  #   networks:
  #     - hvanet

  # peer2.bc.hva.nl:
  #   environment:
  #     - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
  #     - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb2:5984
  #     - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
  #     - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
  #   depends_on:
  #     - couchdb2

  # couchdb3:
  #   container_name: couchdb3
  #   image: hyperledger/fabric-couchdb
  #   environment:
  #     - COUCHDB_USER=
  #     - COUCHDB_PASSWORD=
  #   ports:
  #     - "8984:5984"
  #   networks:
  #     - hvanet

  # peer3.bc.hva.nl:
  #   environment:
  #     - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
  #     - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb3:5984
  #     - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
  #     - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
  #   depends_on:
  #     - couchdb2            

  # couchdb4:
  #   container_name: couchdb4
  #   image: hyperledger/fabric-couchdb
  #   environment:
  #     - COUCHDB_USER=
  #     - COUCHDB_PASSWORD=
  #   ports:
  #     - "9984:5984"
  #   networks:
  #     - hvanet

  # peer4.bc.hva.nl:
  #   environment:
  #     - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
  #     - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb4:5984
  #     - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
  #     - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
  #   depends_on:
  #     - couchdb4