# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.arch.nl:
  peer0.org1.arch.nl:
  peer1.org1.arch.nl:
  peer0.org2.arch.nl:
  peer1.org2.arch.nl:
  peer0.org3.arch.nl:
  peer1.org3.arch.nl:
  

networks:
  Archnet:

services:

  orderer.arch.nl:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.arch.nl
    container_name: orderer.arch.nl
    networks:
      - archnet

  peer0.org1.arch.nl:
    container_name: peer0.org1.arch.nl
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org1.arch.nl
    networks:
      - archnet

  peer1.org1.arch.nl:
    container_name: peer1.org1.arch.nl
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.org1.arch.nl
    networks:
      - archnet

  peer0.org2.arch.nl:
    container_name: peer0.org2.arch.nl
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org2.arch.nl
    networks:
      - archnet

  peer1.org2.arch.nl:
    container_name: peer1.org2.arch.nl
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.org2.arch.nl
    networks:
      - archnet
     
  peer0.org3.arch.nl:
    container_name: peer0.org3.arch.nl
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org3.arch.nl
    networks:
      - archnet
   
  peer1.org3.arch.nl:
    container_name: peer1.org3.arch.nl
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.org3.arch.nl
    networks:
      - archnet
      

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - SYS_CHANNEL=$SYS_CHANNEL
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.org1.arch.nl:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.arch.nl/users/Admin@org1.arch.nl/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../contract:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.arch.nl
      - peer0.org1.arch.nl
      - peer1.org1.arch.nl
      - peer0.org2.arch.nl
      - peer1.org2.arch.nl
      - peer0.org3.arch.nl
      - peer1.org3.arch.nl
    networks:
      - archnet
