# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.hva.nl:
  peer0.bc.hva.nl:
  peer1.bc.hva.nl:
  # peer2.bc.hva.nl:
  # peer3.bc.hva.nl:
  # peer4.bc.hva.nl:    

networks:
  hvanet:

services:

  orderer.hva.nl:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.hva.nl
    container_name: orderer.hva.nl
    networks:
      - hvanet

  peer0.bc.hva.nl:
    container_name: peer0.bc.hva.nl
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.bc.hva.nl
    networks:
      - hvanet

  peer1.bc.hva.nl:
    container_name: peer1.bc.hva.nl
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.bc.hva.nl
    networks:
      - hvanet

  # peer2.bc.hva.nl:
  #   container_name: peer2.bc.hva.nl
  #   extends:
  #     file:  base/docker-compose-base.yaml
  #     service: peer2.bc.hva.nl
  #   networks:
  #     - hvanet

  # peer3.bc.hva.nl:
  #   container_name: peer3.bc.hva.nl
  #   extends:
  #     file:  base/docker-compose-base.yaml
  #     service: peer3.bc.hva.nl
  #   networks:
  #     - hvanet

  # peer4.bc.hva.nl:
  #   container_name: peer4.bc.hva.nl
  #   extends:
  #     file:  base/docker-compose-base.yaml
  #     service: peer4.bc.hva.nl
  #   networks:
  #     - hvanet

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - SYS_CHANNEL=$SYS_CHANNEL
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- FABRIC_LOGGING_SPEC=DEBUG
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.bc.hva.nl:7051
      - CORE_PEER_LOCALMSPID=bcMSP
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/bc.hva.nl/users/Admin@bc.hva.nl/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.hva.nl
      - peer0.bc.hva.nl
      - peer1.bc.hva.nl
      # - peer2.bc.hva.nl
      # - peer3.bc.hva.nl
      # - peer4.bc.hva.nl
    networks:
      - hvanet
