# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer.hva.nl:
    container_name: orderer.hva.nl
    extends:
      file: peer-base.yaml
      service: orderer-base
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/hva.nl/orderers/orderer.hva.nl/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/hva.nl/orderers/orderer.hva.nl/tls/:/var/hyperledger/orderer/tls
        - orderer.hva.nl:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.bc.hva.nl:
    container_name: peer0.bc.hva.nl
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.bc.hva.nl
      - CORE_PEER_ADDRESS=peer0.bc.hva.nl:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      # - CORE_PEER_CHAINCODEADDRESS=peer0.bc.hva.nl:7052
      # - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      # - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.bc.hva.nl:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.bc.hva.nl:7051
      - CORE_PEER_LOCALMSPID=bcMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/bc.hva.nl/peers/peer0.bc.hva.nl/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/bc.hva.nl/peers/peer0.bc.hva.nl/tls:/etc/hyperledger/fabric/tls
        - peer0.bc.hva.nl:/var/hyperledger/production
    ports:
      - 7051:7051
      - 7053:7053

  peer1.bc.hva.nl:
    container_name: peer1.bc.hva.nl
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.bc.hva.nl
      - CORE_PEER_ADDRESS=peer1.bc.hva.nl:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      # - CORE_PEER_CHAINCODEADDRESS=peer1.bc.hva.nl:8052
      # - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.bc.hva.nl:8051
      # - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.bc.hva.nl:7051
      - CORE_PEER_LOCALMSPID=bcMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/bc.hva.nl/peers/peer1.bc.hva.nl/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/bc.hva.nl/peers/peer1.bc.hva.nl/tls:/etc/hyperledger/fabric/tls
        - peer1.bc.hva.nl:/var/hyperledger/production
    ports:
      - 8051:8051
      - 8053:8053

  # peer2.bc.hva.nl:
  #   container_name: peer2.bc.hva.nl
  #   extends:
  #     file: peer-base.yaml
  #     service: peer-base
  #   environment:
  #     - CORE_PEER_ID=peer2.bc.hva.nl
  #     - CORE_PEER_ADDRESS=peer2.bc.hva.nl:9051
  #     - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
  #     # - CORE_PEER_CHAINCODEADDRESS=peer2.bc.hva.nl:9052
  #     # - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
  #     - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2.bc.hva.nl:9051
  #     # - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.bc.hva.nl:7051
  #     - CORE_PEER_LOCALMSPID=bcMSP
  #   volumes:
  #       - /var/run/:/host/var/run/
  #       - ../crypto-config/peerOrganizations/bc.hva.nl/peers/peer2.bc.hva.nl/msp:/etc/hyperledger/fabric/msp
  #       - ../crypto-config/peerOrganizations/bc.hva.nl/peers/peer2.bc.hva.nl/tls:/etc/hyperledger/fabric/tls
  #       - peer2.bc.hva.nl:/var/hyperledger/production
  #   ports:
  #     - 9051:9051

  # peer3.bc.hva.nl:
  #   container_name: peer3.bc.hva.nl
  #   extends:
  #     file: peer-base.yaml
  #     service: peer-base
  #   environment:
  #     - CORE_PEER_ID=peer3.bc.hva.nl
  #     - CORE_PEER_ADDRESS=peer3.bc.hva.nl:10051
  #     - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
  #     # - CORE_PEER_CHAINCODEADDRESS=peer3.bc.hva.nl:10052
  #     # - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
  #     - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer3.bc.hva.nl:10051
  #     # - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.bc.hva.nl:7051
  #     - CORE_PEER_LOCALMSPID=bcMSP
  #   volumes:
  #       - /var/run/:/host/var/run/
  #       - ../crypto-config/peerOrganizations/bc.hva.nl/peers/peer3.bc.hva.nl/msp:/etc/hyperledger/fabric/msp
  #       - ../crypto-config/peerOrganizations/bc.hva.nl/peers/peer3.bc.hva.nl/tls:/etc/hyperledger/fabric/tls
  #       - peer3.bc.hva.nl:/var/hyperledger/production
  #   ports:
  #     - 10051:10051
  #     - 10053:10053

  # peer4.bc.hva.nl:
  #   container_name: peer4.bc.hva.nl
  #   extends:
  #     file: peer-base.yaml
  #     service: peer-base
  #   environment:
  #     - CORE_PEER_ID=peer4.bc.hva.nl
  #     - CORE_PEER_ADDRESS=peer4.bc.hva.nl:11051
  #     - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
  #     # - CORE_PEER_CHAINCODEADDRESS=peer4.bc.hva.nl:11052
  #     # - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11052
  #     - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer4.bc.hva.nl:11051
  #     # - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.bc.hva.nl:7051
  #     - CORE_PEER_LOCALMSPID=bcMSP
  #   volumes:
  #       - /var/run/:/host/var/run/
  #       - ../crypto-config/peerOrganizations/bc.hva.nl/peers/peer4.bc.hva.nl/msp:/etc/hyperledger/fabric/msp
  #       - ../crypto-config/peerOrganizations/bc.hva.nl/peers/peer4.bc.hva.nl/tls:/etc/hyperledger/fabric/tls
  #       - peer4.bc.hva.nl:/var/hyperledger/production
  #   ports:
  #     - 11051:11051   
  #     - 11053:11053                  